#!/usr/bin/env sh
set -eu

. ./scripts/cargo-env

./scripts/check

if [ "${YURU_SKIP_BENCH:-0}" != "1" ]; then
  ./scripts/bench
fi

if [ "${YURU_BENCH_1M_ON_PUSH:-1}" = "1" ] && [ "${YURU_SKIP_BENCH:-0}" != "1" ]; then
  YURU_BENCH_1M=1 cargo bench --bench search plain_search_1m_read_opt_in
fi
