#!/usr/bin/env sh
set -eu

cd "$(dirname "$0")/.."
. ./scripts/cargo-env

cargo bench --bench search

if [ "${YURU_BENCH_1M:-0}" = "1" ]; then
  YURU_BENCH_1M=1 cargo bench --bench search plain_search_1m_read_opt_in
fi
